version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  tmdbzone-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TMDB_API_ACCESS_TOKEN=${TMDB_API_ACCESS_TOKEN}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis

volumes:
  redis_data: